<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CERVED_Service-9ee6fe41-32a6-4a4a-9c12-5bd2f4004cff</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extensions.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SisterBot.CRUD.Repository.Sql\SisterBot.CRUD.Repository.Sql.csproj" />
    <ProjectReference Include="..\SisterBot.CRUD.Repository\SisterBot.CRUD.Repository.csproj" />
  </ItemGroup>
</Project>
